[workspace]
channels = ["conda-forge"]
name = "covid_wastewater"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"

[pypi-dependencies]
jupyterlab = ">=4.5.4, <5"
numpy = ">=2.2.6, <3"
pandas = ">=2.3.3, <3"
polars = ">=1.38.1, <2"
matplotlib = ">=3.10.8, <4"
